#!/system/xbin/ash

# update nvs data on first boot...
if [ ! -f /system/etc/firmware/wl1271-nvs.bin ]; then

/system/bin/nvimport
/system/bin/calibrator set upd_nvs /etc/tiwlan.ini /data/etc/wifi/fw

mount -o remount rw /system
cp /data/etc/wifi/wl1271-nvs.bin /system/etc/firmware/wl1271-nvs.bin
mount -o remount ro /system
fi

insmod /system/lib/modules/wl12xx.ko
insmod /system/lib/modules/wl12xx_sdio.ko
