#!/sbin/sh

#check for trigger
if [ -e /data/data/com.cyanogenmod.ProParts/newKeyboard ]
then
    #be sure system is writeable
    mount -o remount,rw /system

    #remove old keyboard
    rm /system/usr/keychars/pm8059-keypad.kcm
    rm /system/usr/keylayout/pm8058-keypad.kl

    #copy new keyboard and adapt permissions
    cp /data/data/com.cyanogenmod.ProParts/pm8058-keypad.kcm /system/usr/keychars/pm8058-keypad.kcm
    chown 0:0 /system/usr/keychars/pm8058-keypad.kcm
    chmod 644 /system/usr/keychars/pm8058-keypad.kcm
    cp /data/data/com.cyanogenmod.ProParts/pm8058-keypad.kl /system/usr/keylayout/pm8058-keypad.kl
    chown 0:0 /system/usr/keylayout/pm8058-keypad.kl
    chmod 644 /system/usr/keylayout/pm8058-keypad.kl

    #cleanup
    rm /data/data/com.cyanogenmod.ProParts/newKeyboard
    rm /data/data/com.cyanogenmod.ProParts/pm8058-keypad.kcm
    rm /data/data/com.cyanogenmod.ProParts/pm8058-keypad.kl

    sync
    reboot
    #reboot again to make changes happen
fi
#boot normally
