#!/sbin/sh

#be sure system is writeable
mount -o remount,rw /system

#copy new keyboard and adapt permissions
cp /data/data/com.cyanogenmod.ProParts/pm8058-keypad.kcm /system/usr/keychars/pm8058-keypad.kcm
chown 0:0 /system/usr/keychars/pm8058-keypad.kcm
chmod 644 /system/usr/keychars/pm8058-keypad.kcm
cp /data/data/com.cyanogenmod.ProParts/pm8058-keypad.kl /system/usr/keylayout/pm8058-keypad.kl
chown 0:0 /system/usr/keylayout/pm8058-keypad.kl
chmod 644 /system/usr/keylayout/pm8058-keypad.kl

#cleanup
rm /data/data/com.cyanogenmod.ProParts/pm8058-keypad.kcm
rm /data/data/com.cyanogenmod.ProParts/pm8058-keypad.kl

sync
/system/bin/setprop sys.keyboard.change false
reboot
